//
//  Notes.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Notes: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _noteId: String?
    var _content: String?
    var _creationDate: NSNumber?
    var _desCuenta: String?
    var _idCliente: String?
    var _idCuenta: String?
    var _saldoCont: String?
    var _saldoDisp: String?
    var _tipoCuenta: String?
    var _title: String?
    var _updatedDate: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "awssynopsisiosdemo-mobilehub-1926081490-Notes"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_noteId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_noteId" : "noteId",
               "_content" : "content",
               "_creationDate" : "creationDate",
               "_desCuenta" : "desCuenta",
               "_idCliente" : "idCliente",
               "_idCuenta" : "idCuenta",
               "_saldoCont" : "saldoCont",
               "_saldoDisp" : "saldoDisp",
               "_tipoCuenta" : "tipoCuenta",
               "_title" : "title",
               "_updatedDate" : "updatedDate",
        ]
    }
}
